server.port=8080
spring.application.name=siged-idrd

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/siged_idrd}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:siged}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:siged_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://siged:siged_password@localhost:27018/siged_auth?authSource=admin}

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

server.error.include-message=always
